{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "404bcb8a",
   "metadata": {},
   "source": [
    "## Project Documentation: Vanguard Online Process Redesign Analysis\n",
    "\n",
    "\n",
    "# Metadata:\n",
    "\n",
    "\n",
    "- client_id:** Unique ID for each client.\n",
    "- variation: Indicates if a client was part of the experiment.\n",
    "- visitor_id: Unique ID for each client-device combination.\n",
    "- visit_id: Unique ID for each web visit/session.\n",
    "- process_step: Marks each step in the digital process.\n",
    "- date_time: Timestamp of each web activity.\n",
    "- clnt_tenure_yr: Client's tenure with Vanguard in years.\n",
    "- clnt_tenure_mnth: Client's tenure with Vanguard in months.\n",
    "- clnt_age: Age of the client.\n",
    "- gendr: Gender of the client.\n",
    "- num_accts: Number of accounts the client holds with Vanguard.\n",
    "- bal: Total balance spread across all client accounts.\n",
    "- calls_6_mnth: Number of times the client reached out over a call in the past six months.\n",
    "- logons_6_mnth: Frequency of client logins to Vanguard’s platform over the last six months.\n",
    "\n",
    "\n",
    "# Introduction:\n",
    "This project analyzes client behavior data from Vanguard's online process, aiming to understand the impact of a redesign. The documentation covers data exploration, cleaning, analysis, and hypothesis testing.\n",
    "\n",
    "**EDA & Data Cleaning:**\n",
    "\n",
    "\n",
    "Merged multiple datasets.\n",
    "Standardized column names.\n",
    "Cleaned missing values and data inconsistencies.\n",
    "Created visualizations for data exploration.\n",
    "\n",
    "**Client Behavior Analysis:**\n",
    "\n",
    "\n",
    "Analyzed primary client demographics and behavior.\n",
    "Explored client account holdings and balances.\n",
    "Investigated completion rates and errors in the online process.\n",
    "\n",
    "**Performance Metrics:**\n",
    "\n",
    "\n",
    "Calculated completion rates for the control and test groups.\n",
    "Analyzed time spent on each step of the online process.\n",
    "Evaluated error rates, including backward movements.\n",
    "\n",
    "**Redesign Outcome:**\n",
    "\n",
    "\n",
    "Compared new design performance against the old one.\n",
    "Reviewed completion rates, time per step, and errors.\n",
    "\n",
    "**Hypothesis Testing:**\n",
    "\n",
    "\n",
    "Conducted hypothesis tests on completion rates.\n",
    "Assessed completion rate changes with a cost-effectiveness threshold.\n",
    "\n",
    "**Design Effectiveness:**\n",
    "\n",
    "\n",
    "Evaluated experiment structure, randomization, and biases.\n",
    "Assessed the adequacy of the experiment timeframe.\n",
    "Identified potential additional data needs.\n",
    "\n",
    "**Conclusion:**\n",
    "\n",
    "\n",
    "The analysis provides insights into the impact of the online process redesign on client behavior and completion rates. Further experimentation or data collection may enhance the analysis.\n",
    "\n",
    "# Libraries Used:\n",
    "- pandas\n",
    "- seaborn\n",
    "- matplotlib.pyplot\n",
    "- numpy\n",
    "- scipy.stats\n",
    "- glob\n",
    "- statsmodels\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "598e152a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
